// packages/insights/src/root.tsx
import './global.css';
import { component$ } from '@builder.io/qwik';
import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';
import { Insights } from '@khulnasoft.com/qwik-labs';
import { RouterHead } from './components/router-head/router-head';
export default component$(() => {
  return (
    <QwikCityProvider>
      <head>
        <meta charset="utf-8" />
        <link rel="manifest" href="/manifest.json" />
        <RouterHead />
        <Insights
          publicApiKey={import.meta.env.PUBLIC_QWIK_INSIGHTS_KEY}
          postUrl="/api/v1/${publicApiKey}/post/"
        />
      </head>
      <body lang="en">
        <RouterOutlet />
        <ServiceWorkerRegister />
      </body>
    </QwikCityProvider>
  );
});

// starters/apps/qwikcity-test/src/root.tsx
import { QwikCityProvider, RouterOutlet } from "@khulnasoft.com/qwik-city";
import { SomeProvider } from "./components/provider/provider";
import { RouterHead } from "./components/router-head/router-head";
import "./global.css";

export default function Root() {
  return (
    <SomeProvider>
      <QwikCityProvider>
        <head>
          <meta charset="utf-8" />
          <RouterHead />
        </head>
        <body>
          <RouterOutlet />
        </body>
      </QwikCityProvider>
    </SomeProvider>
  );
}
